[project]
name = "cryosaur"
version = "0.1.1"
description = "Resources and scripts for investigating ultrastructure using in situ cryoEM"
readme = "README.md"
authors = [
    { name = "Sam Holland", email = "hol_sam@icloud.com" }
]
requires-python = ">=3.14"
dependencies = [
    "jinja2>=3.1.6",
    "loguru>=0.7.3",
    "mrcfile>=1.5.4",
    "pydantic>=2.13.4",
    "starfile>=0.5.13",
    "typer>=0.27.1",
]

[project.scripts]
cryosaur = "cryosaur.cli:cryosaur"

[build-system]
requires = ["uv_build>=0.11.26,<0.12.0"]
build-backend = "uv_build"
